FROM cbuisson/chef-server

# Configure SSH with pem files
COPY files/chef_env_rsa /root/.ssh/chef_env_rsa
COPY files/chef_env_rsa.pub /root/.ssh/authorized_keys

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
      apt-get install -y vim ssh && \
      mkdir /var/run/sshd && \
      chmod 0755 /var/run/sshd && \
      echo "root:toor" | chpasswd && \
      #sed -ri 's/^#?PasswordAuthentication\s+.*/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
      sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
      sed -ri 's/UsePAM\syes/#UsePAM yes/g' /etc/ssh/sshd_config && \
      sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd && \
      rm -rf /var/lib/apt/lists/

#RUN echo 'Creating pem files associated with chef environment in /etc/chef' && \
#      chef-server-ctl user-create admin An Admin admin@my.org p@ssw0rd1 --filename /etc/chef/admin.pem && \
#      chef-server-ctl org-create my_org my_org --association_user admin --filename /etc/chef/my_org-validator.pem

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]