---
name: Test chef-test-lab
on:
  push:
  pull_request:

jobs:
  tests:
    name: Build, configure, and test chef-test-lab
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v3

      - name: Run basic test
        run: |
          pushd docker/basic
          bash create_ssh_key.sh
          docker-compose up -d --build
          echo "Sleeping for 12 minutes (720 seconds) while waiting for the chef environment to finish building."
          sleep 720
          # Pre-work to enroll agent with chef server
          docker exec -i basic-chef-workstation /bin/bash -c "cd /root/.chef/cookbooks && rm -rf chef-client && knife supermarket download chef-client && tar -xvf chef-client-*; rm *tar*"
          docker exec -i basic-chef-workstation /bin/bash -c "cd /root/.chef/cookbooks && cp hello/Berksfile chef-client/Berksfile"
          docker exec -i basic-chef-workstation /bin/bash -c "cd /root/.chef/cookbooks/chef-client && berks install && berks upload"
          docker exec -i basic-chef-workstation /bin/bash -c "cd /root/.chef/ && knife ssl fetch && knife upload cookbooks"
          docker exec -i basic-chef-workstation knife vault create secret_vault mysql_pw '{"user": "mysql", "password": "TheM0stS3cr3T!!!"}'
          # Bootstrap agent with chef server
          docker exec -i basic-chef-workstation /bin/bash -c "knife bootstrap chef-agent-1 -u root -P toor --sudo -N chef-agent-1 --run-list 'recipe[hello], recipe[chef-client::config]'"
          docker ps
          popd

      - name: Destroy basic test environment
        run: |
          pushd docker/basic
          docker-compose down -v
          popd

      - name: Run extended test
        run: |
          pushd docker/extended
          bash create_ssh_key.sh
          docker-compose up -d --build
          echo "Sleeping for 12 minutes (720 seconds) while waiting for the chef environment to finish building."
          sleep 720
          docker exec -i extended-chef-workstation /bin/bash -c "mkdir -p /root/.chef/data_bags"
          docker exec -i extended-chef-workstation /bin/bash -c "cd /root/.chef/cookbooks && rm -rf chef-client && knife supermarket download chef-client && tar -xvf chef-client-*; rm *tar*"
          docker exec -i extended-chef-workstation /bin/bash -c "cd /root/.chef/cookbooks && cp hello/Berksfile chef-client/Berksfile"
          docker exec -i extended-chef-workstation /bin/bash -c "cd /root/.chef/cookbooks/chef-client && berks install && berks upload"
          docker exec -i extended-chef-workstation /bin/bash -c "cd /root/.chef/ && knife ssl fetch && knife upload cookbooks"
          docker exec -i extended-chef-workstation knife vault create secret_vault mysql_pw '{"user": "mysql", "password": "TheM0stS3cr3T!!!"}'
          # Bootstrap agent with chef server
          docker exec -i extended-chef-workstation /bin/bash -c "knife bootstrap chef-agent-1 -u root -P toor --sudo -N chef-agent-1 --run-list 'recipe[hello], recipe[chef-client::config]'"
          docker ps
          popd

      - name: Destroy extended test environment
        run: |
          pushd docker/extended
          docker-compose down -v
          popd

      - name: Report failure
        uses: nashmaniac/create-issue-action@v1.1
        # Only report failures of pushes
        # (PRs have are visible through the Checks
        # section) to the default branch
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          title: 🐛 Chef lab tests failed for ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: kind/bug
          body: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
